version: 0.0
os: linux
actions:
- action: "Copy files from  backend/dev"
  source_path: " /scripts/Dockerfile.txt"
  target_path: "/opt/codedeploy-agent/"
- action: "Copy files"
  source_path: "/index.htm"
  target_path: "/opt/codedeploy-agent/"
hooks:	
  BeforeInstall:	 
    - location: scripts/install_dependencies	   
      timeout: 300	     
      runas: root	      
    - location: scripts/start_server   
      timeout: 300	     
      runas: root    
