version: 0.0
os: linux
files:	
  - source: /scripts/Dockerfile.txt	  
    destination: /opt/codedeploy-agent/
files:	
  - source: /index.html	  
    destination: /opt/codedeploy-agent/
hooks:	
  BeforeInstall:	 
    - location: scripts/install_dependencies	   
      timeout: 300	     
      runas: root	      
    - location: scripts/start_server   
      timeout: 300	     
      runas: root    
